### ISSUE TITLE
freebsd + arm returns large negative values

### ISSUE THREAD

**Issue by jsirianni** [observIQ/disk-usage#7]
ARM v7 (added print statements to: `disk-usage_unix.go`
```    
} else {
        all  := int(fs.Blocks * uint64(fs.Bsize))
        free := int(fs.Bfree * uint64(fs.Bsize))
        used := int(all - free)
        percentage := int((float64(used) / float64(all)) * 100)

        fmt.Println(strconv.Itoa(all))
        fmt.Println(strconv.Itoa(free))
        fmt.Println(strconv.Itoa(used))
        fmt.Println(strconv.Itoa(percentage))
```

```
./disk-usage-arm.bin -t 0
-1221693440
-1963544576
741851136
-60
Disk usage healthy: /
```

**Comment by jsirianni** [comment]
Not sure if this is still a problem. I have access to some ARM hardware but it may be outdated (old raspberry pie and Netgate hardware).

**Comment by Shakattack76** [comment]
> ARM v7 (added print statements to: `disk-usage_unix.go`
> ```    
> } else {
>         all  := int(fs.Blocks * uint64(fs.Bsize))
>         free := int(fs.Bfree * uint64(fs.Bsize))
>         used := int(all - free)
>         percentage := int((float64(used) / float64(all)) * 100)
> 
>         fmt.Println(strconv.Itoa(all))
>         fmt.Println(strconv.Itoa(free))
>         fmt.Println(strconv.Itoa(used))
>         fmt.Println(strconv.Itoa(percentage))
> ```
> 
> 
> ```
> ./disk-usage-arm.bin -t 0
> -1221693440
> -1963544576
> 741851136
> -60
> Disk usage healthy: /
> ```
